services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    ports:
      - "8080:3000"  # Исправлено с 80 на 3000
    restart: unless-stopped
    environment:
      - NODE_ENV=production